package com.test.bean;

import java.util.Date;

public class TestEnum {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testenum.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testenum.timeInfo
     *
     * @mbggenerated
     */
    private Date timeinfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testenum.id
     *
     * @return the value of testenum.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testenum.id
     *
     * @param id the value for testenum.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testenum.timeInfo
     *
     * @return the value of testenum.timeInfo
     *
     * @mbggenerated
     */
    public Date getTimeinfo() {
        return timeinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testenum.timeInfo
     *
     * @param timeinfo the value for testenum.timeInfo
     *
     * @mbggenerated
     */
    public void setTimeinfo(Date timeinfo) {
        this.timeinfo = timeinfo;
    }
}